version: '3.8'

services:
  app:
    image: guidedogsalice/alice_guidedogs
    platform: linux/x86_64
    restart: always

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - .infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app