version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: guidedogsalice/alice_guidedogs
    platform: linux/x86_64
    restart: always

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/infra/nginx/default.conf
    depends_on:
      - app