TRANSITIONS = [
    {
        "trigger": "trigger_training_center",
        "source": "start",
        "dest": "=",
        "before": "get_training_center",
    },
    {
        "trigger": "trigger_staff",
        "source": "start",
        "dest": "=",
        "before": "get_staff",
    },
    {
        "trigger": "trigger_accommodation",
        "source": "start",
        "dest": "=",
        "before": "get_accommodation",
    },
    {
        "trigger": "trigger_facility",
        "source": "start",
        "dest": "=",
        "before": "get_facility",
    },
    {
        "trigger": "trigger_training",
        "source": "start",
        "dest": "training",
        "before": "get_training",
    },
    {
        "trigger": "trigger_quiz",
        "source": "start",
        "dest": "quiz",
        "before": "get_quiz",
    },
    {
        "trigger": "trigger_legislation",
        "source": "start",
        "dest": "legislation",
        "before": "get_legislation",
        "after": "_save_state",
    },
    {
        "trigger": "trigger_accessibility",
        "source": "legislation",
        "dest": "legislation",
        "before": "get_accessibility",
    },
    {
        "trigger": "trigger_guide_dog_transportation",
        "source": "legislation",
        "dest": "legislation",
        "before": "get_guide_dog_transportation",
    },
    {
        "trigger": "trigger_self_defense",
        "source": "legislation",
        "dest": "legislation",
        "before": "get_self_defense",
    },
    {
        "trigger": "trigger_discounts_free_services",
        "source": "start",
        "dest": "discounts_free_services",
        "before": "get_discounts_free_services",
        "after": "_save_state",
    },
    {
        "trigger": "trigger_food",
        "source": "discounts_free_services",
        "dest": "discounts_free_services",
        "before": "get_food",
    },
    {
        "trigger": "trigger_delicacy",
        "source": "discounts_free_services",
        "dest": "discounts_free_services",
        "before": "get_delicacy",
    },
    {
        "trigger": "trigger_veterinaries",
        "source": "discounts_free_services",
        "dest": "discounts_free_services",
        "before": "get_veterinaries",
    },
    {
        "trigger": "trigger_support_services_blind",
        "source": "start",
        "dest": "=",
        "before": "get_support_services_blind",
    },
    {
        "trigger": "trigger_launch_podcast",
        "source": "start",
        "dest": "=",
        "before": "get_launch_podcast",
    },
    {
        "trigger": "trigger_services_for_blind",
        "source": "start",
        "dest": "services_for_blind",
        "before": "get_services_for_blind",
        "after": "_save_state",
    },
    {
        "trigger": "trigger_regional_clubs",
        "source": "services_for_blind",
        "dest": "services_for_blind",
        "before": "get_regional_clubs",
    },
    {
        "trigger": "trigger_special_view_foundation",
        "source": "services_for_blind",
        "dest": "services_for_blind",
        "before": "get_special_view_foundation",
    },
    {
        "trigger": "trigger_help",
        "source": "*",
        "dest": "help",
        "before": "get_help",
    },
    {
        "trigger": "trigger_help_phrase",
        "source": "help",
        "dest": "help",
        "before": "get_help_phrase",
    },
    {
        "trigger": "trigger_help_navigation",
        "source": "help",
        "dest": "help",
        "before": "get_help_navigation",
    },
    {
        "trigger": "trigger_help_exit",
        "source": "help",
        "dest": "=",
        "before": "get_help_exit",
        "after": "_return_to_original_state",
    },
    {
        "trigger": "trigger_legislation_exit",
        "source": "legislation",
        "dest": "=",
        "before": "get_legislation_exit",
        "after": "_return_to_original_state",
    },
    {
        "trigger": "trigger_discounts_free_services_exit",
        "source": "discounts_free_services",
        "dest": "=",
        "before": "get_discounts_free_services_exit",
        "after": "_return_to_original_state",
    },
    {
        "trigger": "trigger_services_for_blind_exit",
        "source": "services_for_blind",
        "dest": "=",
        "before": "get_services_for_blind_exit",
        "after": "_return_to_original_state",
    },
]
